# coding: utf-8

"""
    SLHPC23 Arena

    **SAP Labs Hungary Programming Competition 2023 Arena server**.  You can find more information about the game and the competititon rules at [github/SLH_SPC_2022](https://github.com/afarago/SLH_SPC_2022).   For a test run, you can use the crash test dummy user `000000000000000000000000/dummypass`.   *Note: All the APIs expect and return application/json*.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: DL SLHPC23 <DL_637A3F6466D808029A65636A@global.corp.sap>
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class DeleteMatchRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'comment': 'str',
        'winner_id': 'str'
    }

    attribute_map = {
        'comment': 'comment',
        'winner_id': 'winnerId'
    }

    def __init__(self, comment=None, winner_id=None, local_vars_configuration=None):  # noqa: E501
        """DeleteMatchRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._comment = None
        self._winner_id = None
        self.discriminator = None

        if comment is not None:
            self.comment = comment
        self.winner_id = winner_id

    @property
    def comment(self):
        """Gets the comment of this DeleteMatchRequest.  # noqa: E501


        :return: The comment of this DeleteMatchRequest.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this DeleteMatchRequest.


        :param comment: The comment of this DeleteMatchRequest.  # noqa: E501
        :type comment: str
        """

        self._comment = comment

    @property
    def winner_id(self):
        """Gets the winner_id of this DeleteMatchRequest.  # noqa: E501

        Stringified Object Id.  # noqa: E501

        :return: The winner_id of this DeleteMatchRequest.  # noqa: E501
        :rtype: str
        """
        return self._winner_id

    @winner_id.setter
    def winner_id(self, winner_id):
        """Sets the winner_id of this DeleteMatchRequest.

        Stringified Object Id.  # noqa: E501

        :param winner_id: The winner_id of this DeleteMatchRequest.  # noqa: E501
        :type winner_id: str
        """
        if self.local_vars_configuration.client_side_validation and winner_id is None:  # noqa: E501
            raise ValueError("Invalid value for `winner_id`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                winner_id is not None and not re.search(r'[0-9a-f]{24}|[0-9a-f]{12}', winner_id)):  # noqa: E501
            raise ValueError(r"Invalid value for `winner_id`, must be a follow pattern or equal to `/[0-9a-f]{24}|[0-9a-f]{12}/`")  # noqa: E501

        self._winner_id = winner_id

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeleteMatchRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DeleteMatchRequest):
            return True

        return self.to_dict() != other.to_dict()
