# coding: utf-8

"""
    SLHPC23 Arena

    **SAP Labs Hungary Programming Competition 2023 Arena server**.  You can find more information about the game and the competititon rules at [github/SLH_SPC_2022](https://github.com/afarago/SLH_SPC_2022).   For a test run, you can use the crash test dummy user `000000000000000000000000/dummypass`.   *Note: All the APIs expect and return application/json*.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: DL SLHPC23 <DL_637A3F6466D808029A65636A@global.corp.sap>
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class IStateDelta(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'draw_pile': 'IStateDeltaStack',
        'discard_pile': 'IStateDeltaStack',
        'banks': 'list[IStateDeltaStack]'
    }

    attribute_map = {
        'draw_pile': 'drawPile',
        'discard_pile': 'discardPile',
        'banks': 'banks'
    }

    def __init__(self, draw_pile=None, discard_pile=None, banks=None, local_vars_configuration=None):  # noqa: E501
        """IStateDelta - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._draw_pile = None
        self._discard_pile = None
        self._banks = None
        self.discriminator = None

        if draw_pile is not None:
            self.draw_pile = draw_pile
        if discard_pile is not None:
            self.discard_pile = discard_pile
        if banks is not None:
            self.banks = banks

    @property
    def draw_pile(self):
        """Gets the draw_pile of this IStateDelta.  # noqa: E501


        :return: The draw_pile of this IStateDelta.  # noqa: E501
        :rtype: IStateDeltaStack
        """
        return self._draw_pile

    @draw_pile.setter
    def draw_pile(self, draw_pile):
        """Sets the draw_pile of this IStateDelta.


        :param draw_pile: The draw_pile of this IStateDelta.  # noqa: E501
        :type draw_pile: IStateDeltaStack
        """

        self._draw_pile = draw_pile

    @property
    def discard_pile(self):
        """Gets the discard_pile of this IStateDelta.  # noqa: E501


        :return: The discard_pile of this IStateDelta.  # noqa: E501
        :rtype: IStateDeltaStack
        """
        return self._discard_pile

    @discard_pile.setter
    def discard_pile(self, discard_pile):
        """Sets the discard_pile of this IStateDelta.


        :param discard_pile: The discard_pile of this IStateDelta.  # noqa: E501
        :type discard_pile: IStateDeltaStack
        """

        self._discard_pile = discard_pile

    @property
    def banks(self):
        """Gets the banks of this IStateDelta.  # noqa: E501


        :return: The banks of this IStateDelta.  # noqa: E501
        :rtype: list[IStateDeltaStack]
        """
        return self._banks

    @banks.setter
    def banks(self, banks):
        """Sets the banks of this IStateDelta.


        :param banks: The banks of this IStateDelta.  # noqa: E501
        :type banks: list[IStateDeltaStack]
        """

        self._banks = banks

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IStateDelta):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IStateDelta):
            return True

        return self.to_dict() != other.to_dict()
