# coding: utf-8

"""
    SLHPC23 Arena

    **SAP Labs Hungary Programming Competition 2023 Arena server**.  You can find more information about the game and the competititon rules at [github/SLH_SPC_2022](https://github.com/afarago/SLH_SPC_2022).   For a test run, you can use the crash test dummy user `000000000000000000000000/dummypass`.   *Note: All the APIs expect and return application/json*.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: DL SLHPC23 <DL_637A3F6466D808029A65636A@global.corp.sap>
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class IUserAction(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'etype': 'MatchActionType',
        'effect': 'CardEffectResponse',
        'autopick': 'AutoPickOptions'
    }

    attribute_map = {
        'etype': 'etype',
        'effect': 'effect',
        'autopick': 'autopick'
    }

    def __init__(self, etype=None, effect=None, autopick=None, local_vars_configuration=None):  # noqa: E501
        """IUserAction - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._etype = None
        self._effect = None
        self._autopick = None
        self.discriminator = None

        if etype is not None:
            self.etype = etype
        if effect is not None:
            self.effect = effect
        if autopick is not None:
            self.autopick = autopick

    @property
    def etype(self):
        """Gets the etype of this IUserAction.  # noqa: E501


        :return: The etype of this IUserAction.  # noqa: E501
        :rtype: MatchActionType
        """
        return self._etype

    @etype.setter
    def etype(self, etype):
        """Sets the etype of this IUserAction.


        :param etype: The etype of this IUserAction.  # noqa: E501
        :type etype: MatchActionType
        """

        self._etype = etype

    @property
    def effect(self):
        """Gets the effect of this IUserAction.  # noqa: E501


        :return: The effect of this IUserAction.  # noqa: E501
        :rtype: CardEffectResponse
        """
        return self._effect

    @effect.setter
    def effect(self, effect):
        """Sets the effect of this IUserAction.


        :param effect: The effect of this IUserAction.  # noqa: E501
        :type effect: CardEffectResponse
        """

        self._effect = effect

    @property
    def autopick(self):
        """Gets the autopick of this IUserAction.  # noqa: E501


        :return: The autopick of this IUserAction.  # noqa: E501
        :rtype: AutoPickOptions
        """
        return self._autopick

    @autopick.setter
    def autopick(self, autopick):
        """Sets the autopick of this IUserAction.


        :param autopick: The autopick of this IUserAction.  # noqa: E501
        :type autopick: AutoPickOptions
        """

        self._autopick = autopick

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IUserAction):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IUserAction):
            return True

        return self.to_dict() != other.to_dict()
