# coding: utf-8

"""
    SLHPC23 Arena

    **SAP Labs Hungary Programming Competition 2023 Arena server**.  You can find more information about the game and the competititon rules at [github/SLH_SPC_2022](https://github.com/afarago/SLH_SPC_2022).   For a test run, you can use the crash test dummy user `000000000000000000000000/dummypass`.   *Note: All the APIs expect and return application/json*.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: DL SLHPC23 <DL_637A3F6466D808029A65636A@global.corp.sap>
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class MatchCreationParams(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'players': 'list[str]',
        'tags': 'list[str]',
        'draw_pile': 'list[Card]',
        'discard_pile': 'list[Card]',
        'banks': 'list[list[Card]]',
        'random_seed': 'str'
    }

    attribute_map = {
        'players': 'players',
        'tags': 'tags',
        'draw_pile': 'drawPile',
        'discard_pile': 'discardPile',
        'banks': 'banks',
        'random_seed': 'randomSeed'
    }

    def __init__(self, players=None, tags=None, draw_pile=None, discard_pile=None, banks=None, random_seed=None, local_vars_configuration=None):  # noqa: E501
        """MatchCreationParams - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._players = None
        self._tags = None
        self._draw_pile = None
        self._discard_pile = None
        self._banks = None
        self._random_seed = None
        self.discriminator = None

        if players is not None:
            self.players = players
        if tags is not None:
            self.tags = tags
        if draw_pile is not None:
            self.draw_pile = draw_pile
        if discard_pile is not None:
            self.discard_pile = discard_pile
        if banks is not None:
            self.banks = banks
        if random_seed is not None:
            self.random_seed = random_seed

    @property
    def players(self):
        """Gets the players of this MatchCreationParams.  # noqa: E501

        List of players. Omit to request a 'practice' match.  # noqa: E501

        :return: The players of this MatchCreationParams.  # noqa: E501
        :rtype: list[str]
        """
        return self._players

    @players.setter
    def players(self, players):
        """Sets the players of this MatchCreationParams.

        List of players. Omit to request a 'practice' match.  # noqa: E501

        :param players: The players of this MatchCreationParams.  # noqa: E501
        :type players: list[str]
        """
        if (self.local_vars_configuration.client_side_validation and
                players is not None and len(players) > 2):
            raise ValueError("Invalid value for `players`, number of items must be less than or equal to `2`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                players is not None and len(players) < 2):
            raise ValueError("Invalid value for `players`, number of items must be greater than or equal to `2`")  # noqa: E501

        self._players = players

    @property
    def tags(self):
        """Gets the tags of this MatchCreationParams.  # noqa: E501

        Tags to add to match for later filtering  # noqa: E501

        :return: The tags of this MatchCreationParams.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this MatchCreationParams.

        Tags to add to match for later filtering  # noqa: E501

        :param tags: The tags of this MatchCreationParams.  # noqa: E501
        :type tags: list[str]
        """

        self._tags = tags

    @property
    def draw_pile(self):
        """Gets the draw_pile of this MatchCreationParams.  # noqa: E501

        [Debug purposes] Draw pile initial contents of cards. When omitted default will be generated.  # noqa: E501

        :return: The draw_pile of this MatchCreationParams.  # noqa: E501
        :rtype: list[Card]
        """
        return self._draw_pile

    @draw_pile.setter
    def draw_pile(self, draw_pile):
        """Sets the draw_pile of this MatchCreationParams.

        [Debug purposes] Draw pile initial contents of cards. When omitted default will be generated.  # noqa: E501

        :param draw_pile: The draw_pile of this MatchCreationParams.  # noqa: E501
        :type draw_pile: list[Card]
        """

        self._draw_pile = draw_pile

    @property
    def discard_pile(self):
        """Gets the discard_pile of this MatchCreationParams.  # noqa: E501

        [Debug purposes] Discard pile initial contents of cards. When omitted default will be generated.  # noqa: E501

        :return: The discard_pile of this MatchCreationParams.  # noqa: E501
        :rtype: list[Card]
        """
        return self._discard_pile

    @discard_pile.setter
    def discard_pile(self, discard_pile):
        """Sets the discard_pile of this MatchCreationParams.

        [Debug purposes] Discard pile initial contents of cards. When omitted default will be generated.  # noqa: E501

        :param discard_pile: The discard_pile of this MatchCreationParams.  # noqa: E501
        :type discard_pile: list[Card]
        """

        self._discard_pile = discard_pile

    @property
    def banks(self):
        """Gets the banks of this MatchCreationParams.  # noqa: E501

        [Debug purposes] Banks initial contents of cards. When omitted match will start with empty banks.  # noqa: E501

        :return: The banks of this MatchCreationParams.  # noqa: E501
        :rtype: list[list[Card]]
        """
        return self._banks

    @banks.setter
    def banks(self, banks):
        """Sets the banks of this MatchCreationParams.

        [Debug purposes] Banks initial contents of cards. When omitted match will start with empty banks.  # noqa: E501

        :param banks: The banks of this MatchCreationParams.  # noqa: E501
        :type banks: list[list[Card]]
        """

        self._banks = banks

    @property
    def random_seed(self):
        """Gets the random_seed of this MatchCreationParams.  # noqa: E501

        [Debug purposes] Optional seed value for pseudorandom generator used for randomization of starting player, card drawing.  Match creation returns a the input or generated seed so you can recreate any game during development.  To ignore randomization and pick first item always use \"norandom\".  # noqa: E501

        :return: The random_seed of this MatchCreationParams.  # noqa: E501
        :rtype: str
        """
        return self._random_seed

    @random_seed.setter
    def random_seed(self, random_seed):
        """Sets the random_seed of this MatchCreationParams.

        [Debug purposes] Optional seed value for pseudorandom generator used for randomization of starting player, card drawing.  Match creation returns a the input or generated seed so you can recreate any game during development.  To ignore randomization and pick first item always use \"norandom\".  # noqa: E501

        :param random_seed: The random_seed of this MatchCreationParams.  # noqa: E501
        :type random_seed: str
        """

        self._random_seed = random_seed

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MatchCreationParams):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MatchCreationParams):
            return True

        return self.to_dict() != other.to_dict()
