/**
 * SLHPC23 Arena
 * **SAP Labs Hungary Programming Competition 2023 Arena server**.  You can find more information about the game and the competititon rules at [github/SLH_SPC_2022](https://github.com/afarago/SLH_SPC_2022).   For a test run, you can use the crash test dummy user `000000000000000000000000/dummypass`.   *Note: All the APIs expect and return application/json*.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: DL SLHPC23 <DL_637A3F6466D808029A65636A@global.corp.sap>
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Card from './Card';
import CardEffectType from './CardEffectType';

/**
 * The CardEffect model module.
 * @module model/CardEffect
 * @version 1.0.0
 */
class CardEffect {
    /**
     * Constructs a new <code>CardEffect</code>.
     * Card effect associated with a special card
     * @alias module:model/CardEffect
     */
    constructor() { 
        
        CardEffect.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CardEffect</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CardEffect} obj Optional instance to populate.
     * @return {module:model/CardEffect} The populated <code>CardEffect</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CardEffect();

            if (data.hasOwnProperty('effectType')) {
                obj['effectType'] = CardEffectType.constructFromObject(data['effectType']);
            }
            if (data.hasOwnProperty('card')) {
                obj['card'] = Card.constructFromObject(data['card']);
            }
            if (data.hasOwnProperty('cards')) {
                obj['cards'] = ApiClient.convertToType(data['cards'], [Card]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CardEffect</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CardEffect</code>.
     */
    static validateJSON(data) {
        // validate the optional field `card`
        if (data['card']) { // data not null
          Card.validateJSON(data['card']);
        }
        if (data['cards']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['cards'])) {
                throw new Error("Expected the field `cards` to be an array in the JSON data but got " + data['cards']);
            }
            // validate the optional field `cards` (array)
            for (const item of data['cards']) {
                Card.validateJsonObject(item);
            };
        }

        return true;
    }


}



/**
 * @member {module:model/CardEffectType} effectType
 */
CardEffect.prototype['effectType'] = undefined;

/**
 * @member {module:model/Card} card
 */
CardEffect.prototype['card'] = undefined;

/**
 * @member {Array.<module:model/Card>} cards
 */
CardEffect.prototype['cards'] = undefined;






export default CardEffect;

