/**
 * SLHPC23 Arena
 * **SAP Labs CEE Hub Programming Competition 2023 Arean server**.  You can find more information about the game and the competititon rules at [github/SLH_SPC_2022](https://github.com/afarago/SLH_SPC_2022).   For a test run, you can use the crash test dummy user `000000000000000000000000/dummypass`.   *Note: All the APIs expect and return application/json*.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: DL SLHPC23 <DL_637A3F6466D808029A65636A@global.corp.sap>
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CardEffectType from './CardEffectType';
import MatchEventDTOResponseToEffectCard from './MatchEventDTOResponseToEffectCard';

/**
 * The CardEffectResponse model module.
 * @module model/CardEffectResponse
 * @version 1.0.0
 */
class CardEffectResponse {
    /**
     * Constructs a new <code>CardEffectResponse</code>.
     * @alias module:model/CardEffectResponse
     */
    constructor() { 
        
        CardEffectResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CardEffectResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CardEffectResponse} obj Optional instance to populate.
     * @return {module:model/CardEffectResponse} The populated <code>CardEffectResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CardEffectResponse();

            if (data.hasOwnProperty('effectType')) {
                obj['effectType'] = CardEffectType.constructFromObject(data['effectType']);
            }
            if (data.hasOwnProperty('card')) {
                obj['card'] = MatchEventDTOResponseToEffectCard.constructFromObject(data['card']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CardEffectResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CardEffectResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `card`
        if (data['card']) { // data not null
          MatchEventDTOResponseToEffectCard.validateJSON(data['card']);
        }

        return true;
    }


}



/**
 * @member {module:model/CardEffectType} effectType
 */
CardEffectResponse.prototype['effectType'] = undefined;

/**
 * @member {module:model/MatchEventDTOResponseToEffectCard} card
 */
CardEffectResponse.prototype['card'] = undefined;






export default CardEffectResponse;

