/**
 * SLHPC23 Arena
 * **SAP Labs Hungary Programming Competition 2023 Arena server**.  You can find more information about the game and the competititon rules at [github/SLH_SPC_2022](https://github.com/afarago/SLH_SPC_2022).   For a test run, you can use the crash test dummy user `000000000000000000000000/dummypass`.   *Note: All the APIs expect and return application/json*.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: DL SLHPC23 <DL_637A3F6466D808029A65636A@global.corp.sap>
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Card from './Card';
import CardEffect from './CardEffect';
import CardEffectType from './CardEffectType';
import IMatchEventParametersResponseToEffectCard from './IMatchEventParametersResponseToEffectCard';
import IStateDelta from './IStateDelta';

/**
 * The IMatchEventParameters model module.
 * @module model/IMatchEventParameters
 * @version 1.0.0
 */
class IMatchEventParameters {
    /**
     * Constructs a new <code>IMatchEventParameters</code>.
     * @alias module:model/IMatchEventParameters
     */
    constructor() { 
        
        IMatchEventParameters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IMatchEventParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IMatchEventParameters} obj Optional instance to populate.
     * @return {module:model/IMatchEventParameters} The populated <code>IMatchEventParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IMatchEventParameters();

            if (data.hasOwnProperty('matchStartedSeed')) {
                obj['matchStartedSeed'] = ApiClient.convertToType(data['matchStartedSeed'], 'String');
            }
            if (data.hasOwnProperty('drawCard')) {
                obj['drawCard'] = Card.constructFromObject(data['drawCard']);
            }
            if (data.hasOwnProperty('cardPlayedEffect')) {
                obj['cardPlayedEffect'] = CardEffect.constructFromObject(data['cardPlayedEffect']);
            }
            if (data.hasOwnProperty('cardPlacedToPlayAreaCard')) {
                obj['cardPlacedToPlayAreaCard'] = Card.constructFromObject(data['cardPlacedToPlayAreaCard']);
            }
            if (data.hasOwnProperty('cardRemovedFromBankCard')) {
                obj['cardRemovedFromBankCard'] = Card.constructFromObject(data['cardRemovedFromBankCard']);
            }
            if (data.hasOwnProperty('cardRemovedFromBankIndex')) {
                obj['cardRemovedFromBankIndex'] = ApiClient.convertToType(data['cardRemovedFromBankIndex'], 'Number');
            }
            if (data.hasOwnProperty('turnEndedDelta')) {
                obj['turnEndedDelta'] = IStateDelta.constructFromObject(data['turnEndedDelta']);
            }
            if (data.hasOwnProperty('turnEndedIsSuccessful')) {
                obj['turnEndedIsSuccessful'] = ApiClient.convertToType(data['turnEndedIsSuccessful'], 'Boolean');
            }
            if (data.hasOwnProperty('matchEndedScores')) {
                obj['matchEndedScores'] = ApiClient.convertToType(data['matchEndedScores'], ['Number']);
            }
            if (data.hasOwnProperty('matchEndedWinnerIdx')) {
                obj['matchEndedWinnerIdx'] = ApiClient.convertToType(data['matchEndedWinnerIdx'], 'Number');
            }
            if (data.hasOwnProperty('matchEndedComment')) {
                obj['matchEndedComment'] = ApiClient.convertToType(data['matchEndedComment'], 'String');
            }
            if (data.hasOwnProperty('matchEndedTerminated')) {
                obj['matchEndedTerminated'] = ApiClient.convertToType(data['matchEndedTerminated'], 'Boolean');
            }
            if (data.hasOwnProperty('responseToEffectType')) {
                obj['responseToEffectType'] = CardEffectType.constructFromObject(data['responseToEffectType']);
            }
            if (data.hasOwnProperty('responseToEffectCard')) {
                obj['responseToEffectCard'] = IMatchEventParametersResponseToEffectCard.constructFromObject(data['responseToEffectCard']);
            }
            if (data.hasOwnProperty('turnStartedDelta')) {
                obj['turnStartedDelta'] = IStateDelta.constructFromObject(data['turnStartedDelta']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IMatchEventParameters</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IMatchEventParameters</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['matchStartedSeed'] && !(typeof data['matchStartedSeed'] === 'string' || data['matchStartedSeed'] instanceof String)) {
            throw new Error("Expected the field `matchStartedSeed` to be a primitive type in the JSON string but got " + data['matchStartedSeed']);
        }
        // validate the optional field `drawCard`
        if (data['drawCard']) { // data not null
          Card.validateJSON(data['drawCard']);
        }
        // validate the optional field `cardPlayedEffect`
        if (data['cardPlayedEffect']) { // data not null
          CardEffect.validateJSON(data['cardPlayedEffect']);
        }
        // validate the optional field `cardPlacedToPlayAreaCard`
        if (data['cardPlacedToPlayAreaCard']) { // data not null
          Card.validateJSON(data['cardPlacedToPlayAreaCard']);
        }
        // validate the optional field `cardRemovedFromBankCard`
        if (data['cardRemovedFromBankCard']) { // data not null
          Card.validateJSON(data['cardRemovedFromBankCard']);
        }
        // validate the optional field `turnEndedDelta`
        if (data['turnEndedDelta']) { // data not null
          IStateDelta.validateJSON(data['turnEndedDelta']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['matchEndedScores'])) {
            throw new Error("Expected the field `matchEndedScores` to be an array in the JSON data but got " + data['matchEndedScores']);
        }
        // validate the optional field `matchEndedWinnerIdx`
        if (data['matchEndedWinnerIdx']) { // data not null
          Number.validateJSON(data['matchEndedWinnerIdx']);
        }
        // ensure the json data is a string
        if (data['matchEndedComment'] && !(typeof data['matchEndedComment'] === 'string' || data['matchEndedComment'] instanceof String)) {
            throw new Error("Expected the field `matchEndedComment` to be a primitive type in the JSON string but got " + data['matchEndedComment']);
        }
        // validate the optional field `responseToEffectCard`
        if (data['responseToEffectCard']) { // data not null
          IMatchEventParametersResponseToEffectCard.validateJSON(data['responseToEffectCard']);
        }
        // validate the optional field `turnStartedDelta`
        if (data['turnStartedDelta']) { // data not null
          IStateDelta.validateJSON(data['turnStartedDelta']);
        }

        return true;
    }


}



/**
 * @member {String} matchStartedSeed
 */
IMatchEventParameters.prototype['matchStartedSeed'] = undefined;

/**
 * @member {module:model/Card} drawCard
 */
IMatchEventParameters.prototype['drawCard'] = undefined;

/**
 * @member {module:model/CardEffect} cardPlayedEffect
 */
IMatchEventParameters.prototype['cardPlayedEffect'] = undefined;

/**
 * @member {module:model/Card} cardPlacedToPlayAreaCard
 */
IMatchEventParameters.prototype['cardPlacedToPlayAreaCard'] = undefined;

/**
 * @member {module:model/Card} cardRemovedFromBankCard
 */
IMatchEventParameters.prototype['cardRemovedFromBankCard'] = undefined;

/**
 * @member {Number} cardRemovedFromBankIndex
 */
IMatchEventParameters.prototype['cardRemovedFromBankIndex'] = undefined;

/**
 * @member {module:model/IStateDelta} turnEndedDelta
 */
IMatchEventParameters.prototype['turnEndedDelta'] = undefined;

/**
 * @member {Boolean} turnEndedIsSuccessful
 */
IMatchEventParameters.prototype['turnEndedIsSuccessful'] = undefined;

/**
 * @member {Array.<Number>} matchEndedScores
 */
IMatchEventParameters.prototype['matchEndedScores'] = undefined;

/**
 * @member {Number} matchEndedWinnerIdx
 */
IMatchEventParameters.prototype['matchEndedWinnerIdx'] = undefined;

/**
 * @member {String} matchEndedComment
 */
IMatchEventParameters.prototype['matchEndedComment'] = undefined;

/**
 * @member {Boolean} matchEndedTerminated
 */
IMatchEventParameters.prototype['matchEndedTerminated'] = undefined;

/**
 * @member {module:model/CardEffectType} responseToEffectType
 */
IMatchEventParameters.prototype['responseToEffectType'] = undefined;

/**
 * @member {module:model/IMatchEventParametersResponseToEffectCard} responseToEffectCard
 */
IMatchEventParameters.prototype['responseToEffectCard'] = undefined;

/**
 * @member {module:model/IStateDelta} turnStartedDelta
 */
IMatchEventParameters.prototype['turnStartedDelta'] = undefined;






export default IMatchEventParameters;

