/**
 * SLHPC23 Arena
 * **SAP Labs Hungary Programming Competition 2023 Arena server**.  You can find more information about the game and the competititon rules at [github/SLH_SPC_2022](https://github.com/afarago/SLH_SPC_2022).   For a test run, you can use the crash test dummy user `000000000000000000000000/dummypass`.   *Note: All the APIs expect and return application/json*.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: DL SLHPC23 <DL_637A3F6466D808029A65636A@global.corp.sap>
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IMoveAt model module.
 * @module model/IMoveAt
 * @version 1.0.0
 */
class IMoveAt {
    /**
     * Constructs a new <code>IMoveAt</code>.
     * @alias module:model/IMoveAt
     * @param at {Date} 
     */
    constructor(at) { 
        
        IMoveAt.initialize(this, at);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, at) { 
        obj['at'] = at;
    }

    /**
     * Constructs a <code>IMoveAt</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IMoveAt} obj Optional instance to populate.
     * @return {module:model/IMoveAt} The populated <code>IMoveAt</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IMoveAt();

            if (data.hasOwnProperty('at')) {
                obj['at'] = ApiClient.convertToType(data['at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IMoveAt</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IMoveAt</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of IMoveAt.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

IMoveAt.RequiredProperties = ["at"];

/**
 * @member {Date} at
 */
IMoveAt.prototype['at'] = undefined;






export default IMoveAt;

