/**
 * SLHPC23 Arena
 * **SAP Labs Hungary Programming Competition 2023 Arena server**.  You can find more information about the game and the competititon rules at [github/SLH_SPC_2022](https://github.com/afarago/SLH_SPC_2022).   For a test run, you can use the crash test dummy user `000000000000000000000000/dummypass`.   *Note: All the APIs expect and return application/json*.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: DL SLHPC23 <DL_637A3F6466D808029A65636A@global.corp.sap>
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class MatchEventType.
* @enum {}
* @readonly
*/
export default class MatchEventType {
    
        /**
         * value: "MatchStarted"
         * @const
         */
        "MatchStarted" = "MatchStarted";

    
        /**
         * value: "TurnStarted"
         * @const
         */
        "TurnStarted" = "TurnStarted";

    
        /**
         * value: "Draw"
         * @const
         */
        "Draw" = "Draw";

    
        /**
         * value: "CardPlayedEffect"
         * @const
         */
        "CardPlayedEffect" = "CardPlayedEffect";

    
        /**
         * value: "ResponseToEffect"
         * @const
         */
        "ResponseToEffect" = "ResponseToEffect";

    
        /**
         * value: "CardPlacedToPlayArea"
         * @const
         */
        "CardPlacedToPlayArea" = "CardPlacedToPlayArea";

    
        /**
         * value: "CardRemovedFromBank"
         * @const
         */
        "CardRemovedFromBank" = "CardRemovedFromBank";

    
        /**
         * value: "TurnEnded"
         * @const
         */
        "TurnEnded" = "TurnEnded";

    
        /**
         * value: "MatchEnded"
         * @const
         */
        "MatchEnded" = "MatchEnded";

    

    /**
    * Returns a <code>MatchEventType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/MatchEventType} The enum <code>MatchEventType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

