/**
 * SLHPC23 Arena
 * **SAP Labs Hungary Programming Competition 2023 Arena server**.  You can find more information about the game and the competititon rules at [github/SLH_SPC_2022](https://github.com/afarago/SLH_SPC_2022).   For a test run, you can use the crash test dummy user `000000000000000000000000/dummypass`.   *Note: All the APIs expect and return application/json*.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: DL SLHPC23 <DL_637A3F6466D808029A65636A@global.corp.sap>
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import State from './State';

/**
 * The MatchResponseReturned2 model module.
 * @module model/MatchResponseReturned2
 * @version 1.0.0
 */
class MatchResponseReturned2 {
    /**
     * Constructs a new <code>MatchResponseReturned2</code>.
     * @alias module:model/MatchResponseReturned2
     */
    constructor() { 
        
        MatchResponseReturned2.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MatchResponseReturned2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MatchResponseReturned2} obj Optional instance to populate.
     * @return {module:model/MatchResponseReturned2} The populated <code>MatchResponseReturned2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MatchResponseReturned2();

            if (data.hasOwnProperty('currentPlayerId')) {
                obj['currentPlayerId'] = ApiClient.convertToType(data['currentPlayerId'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = State.constructFromObject(data['state']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MatchResponseReturned2</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MatchResponseReturned2</code>.
     */
    static validateJSON(data) {
        // validate the optional field `currentPlayerId`
        if (data['currentPlayerId']) { // data not null
          String.validateJSON(data['currentPlayerId']);
        }
        // validate the optional field `state`
        if (data['state']) { // data not null
          State.validateJSON(data['state']);
        }

        return true;
    }


}



/**
 * @member {String} currentPlayerId
 */
MatchResponseReturned2.prototype['currentPlayerId'] = undefined;

/**
 * @member {module:model/State} state
 */
MatchResponseReturned2.prototype['state'] = undefined;






export default MatchResponseReturned2;

