/**
 * SLHPC23 Arena
 * **SAP Labs Hungary Programming Competition 2023 Arena server**.  You can find more information about the game and the competititon rules at [github/SLH_SPC_2022](https://github.com/afarago/SLH_SPC_2022).   For a test run, you can use the crash test dummy user `000000000000000000000000/dummypass`.   *Note: All the APIs expect and return application/json*.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: DL SLHPC23 <DL_637A3F6466D808029A65636A@global.corp.sap>
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MatchResponseMovevent from './MatchResponseMovevent';

/**
 * The MatchResponseAllOf model module.
 * @module model/MatchResponseAllOf
 * @version 1.0.0
 */
class MatchResponseAllOf {
    /**
     * Constructs a new <code>MatchResponseAllOf</code>.
     * @alias module:model/MatchResponseAllOf
     * @param events {Array.<module:model/MatchResponseMovevent>} 
     */
    constructor(events) { 
        
        MatchResponseAllOf.initialize(this, events);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, events) { 
        obj['events'] = events;
    }

    /**
     * Constructs a <code>MatchResponseAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MatchResponseAllOf} obj Optional instance to populate.
     * @return {module:model/MatchResponseAllOf} The populated <code>MatchResponseAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MatchResponseAllOf();

            if (data.hasOwnProperty('events')) {
                obj['events'] = ApiClient.convertToType(data['events'], [MatchResponseMovevent]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MatchResponseAllOf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MatchResponseAllOf</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MatchResponseAllOf.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['events']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['events'])) {
                throw new Error("Expected the field `events` to be an array in the JSON data but got " + data['events']);
            }
            // validate the optional field `events` (array)
            for (const item of data['events']) {
                MatchResponseMovevent.validateJsonObject(item);
            };
        }

        return true;
    }


}

MatchResponseAllOf.RequiredProperties = ["events"];

/**
 * @member {Array.<module:model/MatchResponseMovevent>} events
 */
MatchResponseAllOf.prototype['events'] = undefined;






export default MatchResponseAllOf;

