/**
 * SLHPC23 Arena
 * **SAP Labs Hungary Programming Competition 2023 Arena server**.  You can find more information about the game and the competititon rules at [github/SLH_SPC_2022](https://github.com/afarago/SLH_SPC_2022).   For a test run, you can use the crash test dummy user `000000000000000000000000/dummypass`.   *Note: All the APIs expect and return application/json*.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: DL SLHPC23 <DL_637A3F6466D808029A65636A@global.corp.sap>
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PickPlayerExcludeKeyofPlayerPasswordhash model module.
 * @module model/PickPlayerExcludeKeyofPlayerPasswordhash
 * @version 1.0.0
 */
class PickPlayerExcludeKeyofPlayerPasswordhash {
    /**
     * Constructs a new <code>PickPlayerExcludeKeyofPlayerPasswordhash</code>.
     * From T, pick a set of properties whose keys are in the union K
     * @alias module:model/PickPlayerExcludeKeyofPlayerPasswordhash
     * @param id {String} A class representation of the BSON ObjectId type.
     * @param name {String} 
     */
    constructor(id, name) { 
        
        PickPlayerExcludeKeyofPlayerPasswordhash.initialize(this, id, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name) { 
        obj['_id'] = id;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>PickPlayerExcludeKeyofPlayerPasswordhash</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PickPlayerExcludeKeyofPlayerPasswordhash} obj Optional instance to populate.
     * @return {module:model/PickPlayerExcludeKeyofPlayerPasswordhash} The populated <code>PickPlayerExcludeKeyofPlayerPasswordhash</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PickPlayerExcludeKeyofPlayerPasswordhash();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PickPlayerExcludeKeyofPlayerPasswordhash</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PickPlayerExcludeKeyofPlayerPasswordhash</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PickPlayerExcludeKeyofPlayerPasswordhash.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['_id'] && !(typeof data['_id'] === 'string' || data['_id'] instanceof String)) {
            throw new Error("Expected the field `_id` to be a primitive type in the JSON string but got " + data['_id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }

        return true;
    }


}

PickPlayerExcludeKeyofPlayerPasswordhash.RequiredProperties = ["_id", "name"];

/**
 * A class representation of the BSON ObjectId type.
 * @member {String} _id
 */
PickPlayerExcludeKeyofPlayerPasswordhash.prototype['_id'] = undefined;

/**
 * @member {String} name
 */
PickPlayerExcludeKeyofPlayerPasswordhash.prototype['name'] = undefined;

/**
 * @member {String} email
 */
PickPlayerExcludeKeyofPlayerPasswordhash.prototype['email'] = undefined;






export default PickPlayerExcludeKeyofPlayerPasswordhash;

